name: MIAMIX VIP
description: MIAMIX Curated Lifestyle
url: "https://miamix.vip"

# This tells Jekyll to generate pages for your channels automatically
permalink: /:categories/:title/
# Automatically apply the post.html layout to everything in the _posts folder
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
permalink: /:channel/:url_slug/:language/
